### ISSUE TITLE
add gherkin

### ISSUE THREAD

**Issue by AlbanMinassian** [Colonial-Dev/inkjet#1]
https://github.com/binhtran432k/tree-sitter-gherkin

I have tested inkjet, it's very easy, thanks.

I have a question: where found css for html highlight ?

**Comment by Colonial-Dev** [comment]
Hello!

Unfortunately, I can't add Gherkin at the moment - It's missing a `queries/highlights.scm` file. Without that, Inkjet doesn't know how to highlight the code. Sorry about that!

You could write the queries yourself, or perhaps ask the Gherkin grammar maintainer to do it. Once that's done, I'd be glad to add it.

> I have a question: where found css for html highlight ?

With the bundled HTML formatter, you need to write your own CSS to color the output. Look at `constants::HIGHLIGHT_CLASS_NAMES` for the full list. 

I *am* considering adding a second formatter that supports theming with inline styles, but it'll be a little while before I get around to implementing it.
