### ISSUE TITLE
Vim Grammar

### ISSUE THREAD

**Issue by mhanberg** [Colonial-Dev/inkjet#11]
Hi! I am using this library through the [MDEx](https://github.com/leandrocp/mdex) Elixir library (it uses Rust FFI), and I am interested in highlighting some vimscript.

Grammar: https://github.com/neovim/tree-sitter-vim

**Comment by Colonial-Dev** [comment]
Got it, I'll push an update with Vimscript soon!

**Comment by Colonial-Dev** [comment]
Version `0.10.2` published, featuring Vimscript. MDEx should be able to update easily :)
