### ISSUE TITLE
Pascal and Objective-C Grammar

### ISSUE THREAD

**Issue by clsource** [Colonial-Dev/inkjet#17]
Hi! I am using this library through the [MDEx](https://github.com/leandrocp/mdex) Elixir library.

I have some code snippets that requires
Objective-C and Pascal grammars.

- https://github.com/Isopod/tree-sitter-pascal
- https://github.com/merico-dev/tree-sitter-objc

Thank you so much

**Comment by Colonial-Dev** [comment]
Can do! I'll have to use [this](https://github.com/tree-sitter-grammars/tree-sitter-objc) grammar for Objective-C, as the one you linked doesn't have any highlighting queries.

I should push a new version sometime in the next few days.

**Comment by leandrocp** [comment]
@clsource Pascal is already included in Inkjet. I'll add it to `MDEx`. 

I'm doing some work on the syntax highlighting and will update MDEx soon.

**Comment by Colonial-Dev** [comment]
Apologies for the delay! :bow: 

I got caught up in another project with a deadline. I'll push Objective C support shortly!
