### ISSUE TITLE
Add `shell` alias to `bash`?

### ISSUE THREAD

**Issue by leandrocp** [Colonial-Dev/inkjet#18]
Wdyt about aliasing `shell` to `bash`?

It seems reasonable considering https://github.com/tree-sitter/tree-sitter-bash/blob/f8fb3274f72a30896075585b32b0c54cad65c086/package.json#L59

Btw `sh` resolves as bash so we should at least update the README :)

**Comment by Colonial-Dev** [comment]
As a Bash enjoyer, sounds fine to me! I'm pretty sure Bash is POSIX compliant, which is (presumably) what people will be expecting at minimum when they ask for `shell`.

**Comment by leandrocp** [comment]
Nice, sounds good. I'll push a PR
