### ISSUE TITLE
There some builtin Theme?

### ISSUE THREAD

**Issue by guilhermeprokisch** [Colonial-Dev/inkjet#22]
There are some build in Theme object or I need to always create it?

**Comment by Colonial-Dev** [comment]
There's currently no built-in theme data, but I'm actually planning to release an update soon that converts the system to use Helix editor themes - I'll probably bundle a few common options as `const`s alongside.

**Comment by guilhermeprokisch** [comment]
Nice! Waiting for it.

**Comment by guilhermeprokisch** [comment]
Btw I'm trying to use your library in a terminal context there any Formatter for terminal? I created one myself but not sure if there's buit-in I only found the html one.

**Comment by Colonial-Dev** [comment]
If you're talking about ANSI color escape codes, there is not - right now, only the two HTML formatters are bundled.

**Comment by guilhermeprokisch** [comment]
ok, I if mine works I can send a PR in the future

**Comment by Colonial-Dev** [comment]
Psst, just pushed 0.11.0 w/ a bunch of bundled Helix themes =D

The API is a little different, and I gated your formatter behind the `terminal` feature gate, but I've already updated it to work with the new system.
