### ISSUE TITLE
use spaces instead of hyphens in html classnames

### ISSUE THREAD

**Issue by vidhanio** [Colonial-Dev/inkjet#5]
Hi!

The current constants use `-` to separate selectors, but having each selector being a seperate classname probably makes more sense to use with css. for example, css coloring `.keyword` should also color `.keyword.control`, if `keyword.control` has not been specified already. this is not possible if it was called `keyword-control`.

**Comment by Colonial-Dev** [comment]
Excellent idea! Web dev isn't my strong suit, so I didn't consider this possibility.
